languageCode = "en"
defaultContentLanguage = "en"
title = "Kanari DAO"
# copyright = "Copy, _right?_ :thinking_face:"
baseURL = "/"
relativeURLs = true
uglyURLs = true

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Kanari DAO"
  image = "author.png"  # path relative to static directory

  links = [
     { github = "https://github.com/giorgosn/Decentralized-social-media-account" },
     { email = "mailto:kanari@ethmail.cc" },
     { discord = "https://discord.gg/NHj7wTaA25" },
     { twitter = "https://twitter.com/kanariDAO" },


  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
